### ISSUE TITLE
Server: Data results from queries that stop/error out need to be in sync

### ISSUE THREAD

**Issue by eherman** [ozone-development/meridian#293]
If a query is stopped/errors out on the client, then the server needs to maintain that state.  Currently, an issue can occur when interrupting a query where the server gets additional data. This is an issue because the data that the user sees in the client is different than what is stored on the server.  This is an even bigger issue with the Results History Component (which restores old datasets), because the data that comes back will not appear to be what was in the original dataset to the user.

**Comment by jlfoster2** [comment]
closing this issue.  Good feature and will keep branch around if ever needed.
