### ISSUE TITLE
Bug (proper fix): When more than 10 metadata entries are present, things can go bad

### ISSUE THREAD

**Issue by spines** [ozone-development/meridian#332]
See ticket #331

There are two ways of querying present on the server. 

1) Streaming method (in its own file) - This is the preferred way to say "get me back everything" when you just want all of the results back for a query.
2) Manual Pagination method (getJsonByQuery) - This needs to be updated s.t. the paging information is passed in and the other methods that are calling this function need to either manually paginate or switch to the streaming approach as necessary.

**Comment by tdressel** [comment]
Have 32+ entries in history and no problems.

**Comment by jlfoster2** [comment]
Closing this issue.  This work even before data upload changes.
