### ISSUE TITLE
Add current date/time and version number to client

### ISSUE THREAD

**Issue by cwilmsen** [ozone-development/meridian#352]
Make it so that the version number shows up in the help popup.

PREVIOUSLY: 
Display the current date and time, and the current version number on the client. Where the version number comes from should be dynamic, maybe the system configuration extension?

The date would look good centered in the bottom of the screen.

**Comment by tdressel** [comment]
Is this example version in parenthesis to right of username?

**Comment by cwilmsen** [comment]
There is an option in the help popup that shows this.

**Comment by cwilmsen** [comment]
The original functionality is now in #485.

**Comment by cwilmsen** [comment]
Click on the ? button (help) --> Click on 'About Meridian' (in picture) --> View popup with info, including version number

**Comment by cwilmsen** [comment]
![352 example](https://cloud.githubusercontent.com/assets/1810668/5599161/3bde49b6-9290-11e4-9929-db2846371311.jpeg)
