### ISSUE TITLE
Add index.html to URLs as needed.

### ISSUE THREAD

**Issue by jrdrgz** [ozone-development/meridian#363]
Add index.html to all URLs found in the documentation.
Also change the link found on the tour component.

Remember to make changes in gh-pages as well as the docs/meridian folder.

**Comment by tdressel** [comment]
Confirmed following URL's were update and working....
https://localhost:3000/docs/meridian/index.html
        "Download Meridian" button prompts download to Meridian like it should.
        "View on GitHub" navigates to https://github.com/ozone-development/meridian
         "Launch Meridian" launches Meridian Map in a new browser tab using URL - https://ec2-54-88-124-5.compute-1.amazonaws.com:3000/index.html
https://localhost:3000/docs/meridian/getting-started/index.html
         https://localhost:3000/docs/meridian/getting-started/index.html#startedQuickly
         https://localhost:3000/docs/meridian/getting-started/index.html#accessMeridian
         https://localhost:3000/docs/meridian/getting-started/index.html#embedMeridian
         https://localhost:3000/docs/meridian/getting-started/index.html#requirements
         https://localhost:3000/docs/meridian/getting-started/index.html#withoutGrunt
         https://localhost:3000/docs/meridian/getting-started/index.html#withGrunt
         https://localhost:3000/docs/meridian/getting-started/index.html#resources
https://localhost:3000/docs/meridian/contribute/index.html
         https://localhost:3000/docs/meridian/contribute/index.html#pullRequest
         https://localhost:3000/docs/meridian/contribute/index.html#issues
         https://localhost:3000/docs/meridian/contribute/index.html#styleGuide
https://localhost:3000/docs/meridian/examples/index.html
         https://localhost:3000/docs/meridian/examples/index.html#starting
         https://localhost:3000/docs/meridian/examples/index.html#startingExample
         https://localhost:3000/docs/meridian/examples/index.html#components
         https://localhost:3000/docs/meridian/examples/index.html#componentsRules
         https://localhost:3000/docs/meridian/examples/index.html#componentsExamples
         https://localhost:3000/docs/meridian/examples/index.html#messaging
         https://localhost:3000/docs/meridian/examples/index.html#messagingRules
         https://localhost:3000/docs/meridian/examples/index.html#messagingExamples
         https://localhost:3000/docs/meridian/examples/index.html#sandBoxing
         https://localhost:3000/docs/meridian/examples/index.html#sandBoxingExamples
         https://localhost:3000/docs/meridian/examples/index.html#extensions
         https://localhost:3000/docs/meridian/examples/index.html#extensionsRules
         https://localhost:3000/docs/meridian/examples/index.html#extensionsExamples
         https://localhost:3000/docs/meridian/examples/index.html#meridian
         https://localhost:3000/docs/meridian/examples/index.html#demo
         https://localhost:3000/docs/meridian/examples/index.html#source

**Comment by jrdrgz** [comment]
That covers the actual page.
Also verify that the support component button called 'Meridian Docs" points to: https://localhost:3000/docs/meridian/index.html instead of https://localhost:3000/docs/meridian

Finally, verify the same links sone on your initial test but replacing https://localhost:3000/docs/meridian with http://ozone-development.github.io/meridian

**Comment by tdressel** [comment]
Passed on develop.
