### ISSUE TITLE
Setup documentation needs to be updated

### ISSUE THREAD

**Issue by jlfoster2** [ozone-development/meridian#368]
There are a few things that need to be updated in the setup docs that are vague or incorrect.  This ticket will update starting ES as well as make a note on a few npm libs that are being updated.

**Comment by jlfoster2** [comment]
@Bill345 Lets assign this to new guy when he gets back. :)

**Comment by cwilmsen** [comment]
Where is the pull request for this? 
Seth, if you need help putting in a pull request, let me know, and I'll lead you through it.

**Comment by jlfoster2** [comment]
+1 from Chris.  We need a pull request.

**Comment by sethmussey** [comment]
Will address this tomorrow.

**Comment by jlfoster2** [comment]
@sethmussey can you put your pull request up so we can get this put into next glide?
