### ISSUE TITLE
Closing data grid cause a strip of white at top of screen

### ISSUE THREAD

**Issue by tdressel** [ozone-development/meridian#395]
STR
Run a query
Open Data Grid
Close Data Grid
RESULTS - Data Grid closes and White strip appears at top of screen.
EXPECTED RESULTS - Data Grid closes and a white strip should NOT display at top of the screen.

**Comment by synAe** [comment]
Do not see this in Firefox or Chrome -- may not be an issue since Data Grid uses slickGrid now?

**Comment by cwilmsen** [comment]
No pull request, seems to be fixed already

**Comment by tdressel** [comment]
This is still an issue on develop branch using Firefox and Chrome.

**Comment by cwilmsen** [comment]
Besides Tiff, does anyone else have this issue?

**Comment by synAe** [comment]
I just pulled from develop, I see both in Chrome and Firefox (top of browser screen)
