### ISSUE TITLE
Grunt server does not handle elastic search mapping updates

### ISSUE THREAD

**Issue by jlfoster2** [ozone-development/meridian#403]
This is a placeholder for the bug that @spines mentioned today about having to start elastic search and node separately when making changes to mapping files in elastic search.

**Comment by cwilmsen** [comment]
Grunt now waits for elastic to start up before starting node, allowing the node commands to init indexes in elastic to work.

To test:
-Pull branch
-run 'npm install'
-delete both elastic indexes
-run 'grunt server'
-Refresh elastic head
-make sure that the indexes are there and their metadata properly inited

**Comment by tdressel** [comment]
Looks good on local branch.

**Comment by jlfoster2** [comment]
This is still failing.  I have previous queries that are failing to load in data history.  I dont believe that waiting for the elastic to load data is the entire problem. @cwilmsen we can discuss more
