### ISSUE TITLE
Feature point icons should be consistent throughout the app.

### ISSUE THREAD

**Issue by tdressel** [ozone-development/meridian#445]
The green feature point icon that is created in cmapi mode is a nice icon and should replace the blue feature point icons.

**Comment by jlfoster2** [comment]
Just talked to Dale. The intent of the ticket is to not make all icons the same color.  However, it is make the icons types the same between post messages and and normal querying.  Dale understands and will be working the ticket now.

**Comment by cwilmsen** [comment]
They ARE the same throughout the map. The default cmapi plot specifically tells the application to use a different color marker.

**Comment by jlfoster2** [comment]
They are NOT THE SAME :) All in caps so I win.

**Comment by tdressel** [comment]
Putting back in "In Progress" Dale will fix when he gets license for Photoshop.

**Comment by tdressel** [comment]
Passed in local branch.  Style was approved by group.

**Comment by jrdrgz** [comment]
Tested and both icons look the same, but with different colors. (Query vs CMAPI plot)
Merged for testing.

**Comment by tdressel** [comment]
Passed on develop
