### ISSUE TITLE
BYOD: forget previous file

### ISSUE THREAD

**Issue by cwilmsen** [ozone-development/meridian#454]
On file upload, remove file from the file picker. This means that the user will have to select a new file each time.

Linked to: SCM-258

**Comment by cwilmsen** [comment]
This looks fixed.

**Comment by jlfoster2** [comment]
@tdressel can you validate this and if so close this ticket.

**Comment by tdressel** [comment]
Passed this but created 602.  Although the file is cleared from file field after uploaded it still assumes that file the next time you upload data.

**Comment by tdressel** [comment]
Clears out after file is uploaded. passed on develop.
