### ISSUE TITLE
Refactor datagrid

### ISSUE THREAD

**Issue by cwilmsen** [ozone-development/meridian#463]
Use slickgrid to update the datagrid.

**Comment by tdressel** [comment]
Pulled local branch and tested.
Column reordering - PASSED
Search - PASSED
Open/Close ('x' on data grid) - PASSED
Autosizing column widths - FAILED - When first opening data grid it seems to not be aligned properly until you manually adjust the columns
Manual  column resizing - PASSED
Single Selection - PASSED
Selection Persists - FAILED - Select a row on first page. Navigate to the last page.  The same (location) row but different feature is selected and displaying pop up.  It persists until you get to the last page or go directly to last page. The original pop up should persist.
Paging: next/previous/first/last - PASSED
Paging: select page size - PASSED

**Comment by cwilmsen** [comment]
The column misalignment was only in FF. This should be fixed. The issue with persisting selection is not a problem with me, and worked at least for a while with Tiff.

**Comment by tdressel** [comment]
Pulled local branch and tested.
Column reordering - PASSED
Search - PASSED
Open/Close ('x' on data grid) - PASSED bug is created for white bar at top after closed data grid.
Autosizing column widths - PASSED
Manual column resizing - PASSED
Single Selection - PASSED
Selection Persists - PASSED
Paging: next/previous/first/last - PASSED
Paging: select page size - PASSED

**Comment by tdressel** [comment]
Passed on develop
Column reordering - PASSED
Search - PASSED
Open/Close ('x' on data grid) - PASSED
Autosizing column widths - PASSED
Manual column resizing - PASSED
Single Selection - PASSED
Selection Persists - PASSED
Paging: next/previous/first/last - PASSED
Paging: select page size - PASSED
