### ISSUE TITLE
As an admin need ability to track metrics associated with Meridian

### ISSUE THREAD

**Issue by jlfoster2** [ozone-development/meridian#470]

**Comment by jlfoster2** [comment]
Once Tiff oks this, I will do the merge since the branch is behind.  Will make sure @synAe sits with me to learn  how to do this.

**Comment by tdressel** [comment]
passed on enhancement/470/admin-dashboard-single

**Comment by jlfoster2** [comment]
1.) Exit button does not do anything so probably want to remove it
2.) Dont think user name is referencing name pulled from cert
3.) Message should be displayed if nothing is found from search
4.) Should clear button not only clear search fields but data grid as well?  I guess this goes with point #3 from above.  Looking for comments with this one.

**Comment by synAe** [comment]
Updated with fixes 1 - 4

**Comment by tdressel** [comment]
Passed in local branch

**Comment by tdressel** [comment]
https://localhost:3000/modes/admin/  PASSED

**Comment by synAe** [comment]
Admingrid and search components have been moved into their own /admin folder (file/folder structure)

**Comment by tdressel** [comment]
https://localhost:3000/modes/admin/ worked on dev branch
