### ISSUE TITLE
Datasource configs

### ISSUE THREAD

**Issue by cwilmsen** [ozone-development/meridian#479]
Add an attribute 'datasources' to the sandbox, and put system-wide relevent information in it.
-DATASOURCE_NAME
-DISPLAY_NAME
-SERVER_NAME
-Use this for query tool?
-Use for displaying readable name in datahistory

**Comment by cwilmsen** [comment]
Merged develop back in.

**Comment by tdressel** [comment]
Name , Source and Date display on first data history screen?

**Comment by tdressel** [comment]
Passed on develop.
