### ISSUE TITLE
CMAPI: bad overlay ids

### ISSUE THREAD

**Issue by cwilmsen** [ozone-development/meridian#483]
If a user sends over an overlayId that contains 'bad' things, like #. or spaces, it breaks the system, specifically the timeline. To fix this, make a map of user overlayIds to application created layerIds. This allows the user to still send whatever they want over and still reference it properly, while ensuring that we are using valid things internally.

**Comment by cwilmsen** [comment]
We decided that it is the user's responsibility to send us valid overlay ids. 

This ticket should either be closed, or turned into 'add documentation for what is a valid overlay id'

**Comment by jlfoster2** [comment]
Closing this as already defined in cmapi spec (v1.3.0)
