### ISSUE TITLE
Show client version/current time on screen

### ISSUE THREAD

**Issue by cwilmsen** [ozone-development/meridian#485]
Display the current date and time, and the current version number on the client VISIBLE AT ALL TIMES. This will make screen grabs easier to debug, and helpful for people using grabs in documents.

The date would look good centered in the bottom of the screen.

This was previously #352, which was taken over.

**Comment by jlfoster2** [comment]
Updating requirements for this ticket to only include release date in the support modal.  I think we need to have larger discussions about including date/time/version in the application itself.

**Comment by cwilmsen** [comment]
The original meaning for this ticket is now in #487. 

"Don't fail me again, Admiral" -Darth Vader

**Comment by tdressel** [comment]
Verified the Support/Help modal.

Meridian: Version 0.5.2
Release Date: 01/08/2015
Released under the Apache License v2.0.
Forked from the Open Source Project: Aura JS.

**Comment by tdressel** [comment]
Passed on develop branch
Meridian: Version 0.5.4
Release Date: 01/13/2015
Released under the Apache License v2.0.
Forked from the Open Source Project: Aura JS.
