### ISSUE TITLE
Add layer and single point export capabilities to export component

### ISSUE THREAD

**Issue by jrdrgz** [ozone-development/meridian#486]

**Comment by jrdrgz** [comment]
Pull request submitted. Waiting on additional feedback and design suggestions. @cwilmsen finished most of the logic with the extensions and I made the final UI changes.

**Comment by tdressel** [comment]
Ran three queries.
Selected Export Options button
Select all or one query
Choose CSV Export
Export
The results are exported into a CSV file and they all are viewable in file.
Google Maps is not enabled at this time.
