### ISSUE TITLE
Current date and version number viewable on the client

### ISSUE THREAD

**Issue by cwilmsen** [ozone-development/meridian#487]
This was originally #352, and then it was #485 . Since both of those were hijacked, I'm make this one.

Display the current date and time, and the current version number on the client VISIBLE AT ALL TIMES. This will make screen grabs easier to debug, and helpful for people using grabs in documents.

The date would look good centered in the bottom of the screen.

NOTE: THIS HAS NOTHING TO DO WITH THE SUPPORT MODAL!!!!! It is meant to be shown in the main view, and visible at ALL TIMES.

**Comment by jlfoster2** [comment]
Closing for time being, we can reopen if the need occurs (especially since we will be logging this information into new admin dashboard)
