### ISSUE TITLE
locator throwing error

### ISSUE THREAD

**Issue by cwilmsen** [ozone-development/meridian#489]
Whenever the locator plots a point (using coordinates), it throws an error. This is because the locator static layer does not use clustering, and adding points always tries to do clustering. Make OL/map/features.plotFeatures only try to do clustering if the layer has clustering() as a function.

This might lead to other errors that need to be fixed.

TO TEST:
-Make sure the map is in clustering mode
-Create a point by entering coordinates into the locator bar and hitting 'go'
Expected Result: No error thrown, and a point is plotted

**Comment by tdressel** [comment]
Passed on local branch bug/489/locator-throwing-error

**Comment by tdressel** [comment]
Passed on develop.
