### ISSUE TITLE
Clear toggle basemap button

### ISSUE THREAD

**Issue by cwilmsen** [ozone-development/meridian#490]
Hitting clear changes the state of the basemap button (on the slideout). 
Current:
-Open page (basemap button defaults to on)
-hit clear, accept
Result: basemap button turns to off, but the basemap gallery is stil showing

Expected Result: 
-Open page (basemap button defaults to on)
-hit clear, accept
Result: basemap button stays in sync with the basemap gallery. Since the gallery doesn't toggle on clear, the button should not either.

**Comment by tdressel** [comment]
Passed on local branch bug/490/clear-basemap-toggle
Basemap button defaults to on.
Clear screen
RESULTS - Basemap button remains on. Basemap remains on map.
Turn Basemap button off.
RESULTS - Basemap no longer appears on the screen an button displays in off position
Clear screen
RESULTS - Basemap button remains off. Basemap still doesnt display on screen.

**Comment by tdressel** [comment]
Passed on develop
Basemap button defaults to on.
Clear screen
RESULTS - Basemap button remains on. Basemap remains on map.
Turn Basemap button off.
RESULTS - Basemap no longer appears on the screen an button displays in off position
Clear screen
RESULTS - Basemap button remains off. Basemap still doesnt display on screen.
