### ISSUE TITLE
Hide orphaned queries from data history

### ISSUE THREAD

**Issue by jlfoster2** [ozone-development/meridian#498]
Replicating on this side

**Comment by tdressel** [comment]
Ran two queries.  First one I stopped mid query.  Second I deleted mid query.  Both showed in Data History.  ?????que??????

**Comment by jlfoster2** [comment]
Data is orphaned if it is pushed directly to the map (i.e. cmapi).  There should be no data history for those actions.  Make sense?

**Comment by tdressel** [comment]
Yep now it does.

**Comment by tdressel** [comment]
Tested on local branch enhancement/498/orphaned-queries in cmapi.  Plotted feature and verified it does not display in Data History since it does not have a datasource.

**Comment by tdressel** [comment]
Tested on Develop and passed.
Cleared elasticsearch.  
Started node app.js manually.  
Logged into Cmapi. 
Plotted a feature using pub sub.
RESULTS - This (orphaned) feature did not display in Data History. (Orphaned meaning it did not have a data source associated with it)
Ran a query using query tool
RESULT S- These features displayed in Data History.
