### ISSUE TITLE
Data History | Uploaded files are not populating data source field

### ISSUE THREAD

**Issue by tdressel** [ozone-development/meridian#504]
Uploaded filed are not populating the data source field in the Data History.
STR
Log onto Meridian
Upload kml, csv and geojsn test files
***Verify in http://localhost:9200/_plugin/head/ data source field is populated with "upload"
Go to Data History
RESULTS - Source field is blank.
EXPECTED RESULTS - probably should display what is populated in elasticsearch.

**Comment by tdressel** [comment]
FAILED on local branch

**Comment by jlfoster2** [comment]
Verified and this works on branch.  Passing and merging in.

**Comment by tdressel** [comment]
Passed in develop
