### ISSUE TITLE
New jquery-ui

### ISSUE THREAD

**Issue by cwilmsen** [ozone-development/meridian#515]
We need to bring in a few other jquery-ui modules, specifically slider. Make sure that the manual modifications stay there, and that datagrid does not change styling for the worse.

Linked to SCM-311

**Comment by jlfoster2** [comment]
Is this something that needs to be moved up in priority?

**Comment by cwilmsen** [comment]
Did we need more ui stuff? I know that Dale was using some for his picker. Once we know all we need to include (or we just decide to use everything), we can upload a version.

**Comment by jlfoster2** [comment]
OBE - closing ticket
