### ISSUE TITLE
Black strip displays at top of map when choosing a new feature on data grid.

### ISSUE THREAD

**Issue by tdressel** [ozone-development/meridian#517]
This happens on develop branch
STR-
Run a query
Open data grid
Choose a feature row
RESULTS - The feature pop up details displays on map. Dark strip appears at the top of map then goes away.  Every. 5th or 6th time.
EXPECTED RESULTS - The feature pop up details displays on map. Dark strip SHOULD NOT appear at the top of map. Ever.

**Comment by cwilmsen** [comment]
I do not see this problem, and thus cannot do anything.

**Comment by tdressel** [comment]
I cannot repro this.

**Comment by tdressel** [comment]
Cannot repro on develop.

**Comment by jlfoster2** [comment]
Cant reproduce...closing ticket

**Comment by jlfoster2** [comment]
Closing...can reproduce bug
