### ISSUE TITLE
Layer Export - replace export to Google Maps with geojson

### ISSUE THREAD

**Issue by jlfoster2** [ozone-development/meridian#526]
I would remove the export to Google Maps additional options and replace with geoJson export.  I would also change the extra options section for geojson to include something like changing the marker color, adding an additional value to the properties of message, etc.  The last page has not value in the context of the app.

**Comment by cwilmsen** [comment]
PLEASE PLEASE PLEASE PLEASE DO NOT DO THIS
We will reuse geojson, and adding superfluous options would cause more work. That is why google maps got the options. We will not actually use it.

Also, how would you change the color of the marker? It's going out, not coming in.

**Comment by jrdrgz** [comment]
Here is another suggestion. How about we allow the users to modify what can be sent to the google maps url and make that the additional options? 
We could allow the user to specify the layer google uses:
t=
Sets the kind of map shown. Can be set to:
m – normal  map
k – satellite
h – hybrid
p – terrain

The same can be done to set the language, zoom level, etc. We could make them drop downs and simply add them to the URL.

**Comment by jlfoster2** [comment]
Think we can close this out.  People get the idea of how to use this feature
