### ISSUE TITLE
Layer Export - select all defaults when it shouldnt

### ISSUE THREAD

**Issue by jlfoster2** [ozone-development/meridian#528]
Select all checkbox is selected however layer is not (only one layer present). You can replicate by trying to export a layer(select all) and then exporting a feature.  Come back to layer and select is still checked.

**Comment by cwilmsen** [comment]
Could you please explain this more? I don't think I understand what you are saying. Are you using 'feature' correctly, or did you mean layer?

My testing was:
-Run query
-use export button (no checkboxes selected)
-clicked the 'all' box
-exported
--
-click export toggle again
-Nothing was checked

I also did
-Run query
-use export button (no checkboxes selected)
-clicked the 'all' box
-exported
--
-exported a POINT
--
-Clicked export toggle again
-Nothing was checked

**Comment by jlfoster2** [comment]
this is OBE..closing
