### ISSUE TITLE
CMAPI - view channel compliance

### ISSUE THREAD

**Issue by jlfoster2** [ozone-development/meridian#530]
Bring map.view.zoom in compliance with 1.3.0 spec

**Comment by jlfoster2** [comment]
@cwilmsen the spec calls for finding the most appropriate range in meters.  this dosent make sense for 2d maps.  opening a discussion on the cmapi google groups about this, but not going to support the map.view.zoom channel.

**Comment by cwilmsen** [comment]
Exactly.

**Comment by tdressel** [comment]
Pulled branch. Plotted features.  Zoomed out.  Nothing happens.

**Comment by jlfoster2** [comment]
@tdressel.  Dont think this was tested correctly.  Lets sync tomorrow about the process for testing all CMAPI

**Comment by jlfoster2** [comment]
@tdressel added channels to cmapi test harness to help you with this. take a look and let me know..

**Comment by tdressel** [comment]
Tested and passed following:
map.view.zoom.in
map.view.zoom.out
map.view.zoom.max.extent
map.view.center.feature
map.view.center.location
map.view.center.bounds
map.view.center.data
map.clear

map.view.center.overlay was giving a no data in layer error.

**Comment by tdressel** [comment]
Tested and passed following:
map.view.zoom.in
map.view.zoom.out
map.view.zoom.max.extent
map.view.center.overlay
map.view.center.feature
map.view.center.location
map.view.center.bounds
map.view.center.data
map.clear

**Comment by tdressel** [comment]
passed on dev cmapi
