### ISSUE TITLE
Implement a mechanism for up/down voting new features

### ISSUE THREAD

**Issue by jlfoster2** [ozone-development/meridian#538]
This could be an option (http://pligg.com/about/).  Thoughts?

**Comment by cwilmsen** [comment]
I assume that we would be hosting in on Amazon? 

Also, it looks like this is for 'articles', not tickets. Would we have to also make an article for each ticket? That sounds like an awful lot of upkeep.

**Comment by jlfoster2** [comment]
Can support feature requests.  This is typical crowd sourcing tool that can fitted for anything.  After talking with Sean/Watson today, they are going to get a better direction from customer on how much integration work and requirements tracking we will need to do. Leaving ticket in backlog status for time being.

**Comment by jlfoster2** [comment]
this got shot down...closing this out.
