### ISSUE TITLE
Download CSV, KML, and geoJSON files

### ISSUE THREAD

**Issue by cwilmsen** [ozone-development/meridian#540]
Allow users to download queries into CSV, KML, or geoJSON files.

**Comment by cwilmsen** [comment]
This seems like it also fixes #302 ?

**Comment by tdressel** [comment]
Passed in enhancement/540/download-file-types

**Comment by tdressel** [comment]
Passed on local branch.

**Comment by tdressel** [comment]
Passed in Develop
