### ISSUE TITLE
Move slickgrid css into datagrid component

### ISSUE THREAD

**Issue by jlfoster2** [ozone-development/meridian#543]
Modes break for datagrid because css files for slickgrid are not in the component

**Comment by synAe** [comment]
Updated to retain a 150px minimum width while also being able to correctly 'fill' the full width of the grid

**Comment by tdressel** [comment]
Passed on local branch bug/543/move-slickgrid-css

**Comment by jlfoster2** [comment]
@cwilmsen can you merge this one if you approve of Dales code?

**Comment by tdressel** [comment]
passed on develop
