### ISSUE TITLE
Download file: add query name and source

### ISSUE THREAD

**Issue by cwilmsen** [ozone-development/meridian#550]
Add query name and source to each download feature.

**Comment by cwilmsen** [comment]
Linked to SCM-373

**Comment by cwilmsen** [comment]
Blocked by #540

**Comment by cwilmsen** [comment]
This was added already, maybe a duplicate?

**Comment by jlfoster2** [comment]
yup..closing

**Comment by tdressel** [comment]
Tested anyway.  Was able to upload all three files geo.jsn, kml and csv.  Cleared map.  Restored all three instances and they all uploaded with source and query name.
