### ISSUE TITLE
Add client side coordinate converter and implement into locator tool

### ISSUE THREAD

**Issue by jrdrgz** [ozone-development/meridian#557]

**Comment by jrdrgz** [comment]
The locator tool will accept any of the following formats:
Decimal Degrees (DD/Lat,Lon)
Degrees Minutes Seconds (DMS)
Military Grid Reference System (MGRS)
Universal Transverse Mercator (UTM)

The component will then convert the input to all possible options and return an object containing all formats.

**Comment by jrdrgz** [comment]
To test, you can input any of the following and compare it to the Decimal Degree (dd) coordinate. The plotted point will have the same dd coordinate (sometimes if you round up since OpenLayers has way more precision). MGRS can't have a fractional part in the decimal number. MGRS can have a fractional part in both numbers, so can DMS.

dd: 12.5,14.7
dms: 123000N,144200E
mgrs: 33P VP 6740481862
utm: 33P 467404 1381862

dd: -12.9,32.3
dms: 125400S,321800E
mgrs: 36L VL 2405973819
utm: 36L 424059 8573819

dd: -50.2,-100.1
dms: 501200S,1000600W
mgrs: 14F MK 2149538553
utm: 14F 421495 4438553

**Comment by tdressel** [comment]
Passed on local branch - enhancement/557/clientCoordinateConverter

**Comment by tdressel** [comment]
Passed on develop
