### ISSUE TITLE
Map Status: Update map.status.ready

### ISSUE THREAD

**Issue by cwilmsen** [ozone-development/meridian#558]
Update all of the map.status.ready stuff to work
-state manager
-layers
-cmapi

**Comment by cwilmsen** [comment]
To test:
Go to cmapi page
map.status.ready: {"widgetName":"Meridian","readyState":true} should show up

**Comment by tdressel** [comment]
CMAPI is broke on FF 17.  Chrome works.  Creating bug for this issue
