### ISSUE TITLE
Export to File: Add query name and datasource to file

### ISSUE THREAD

**Issue by cwilmsen** [ozone-development/meridian#565]
Make it so that all exported features have properties for query name and datasource

**Comment by cwilmsen** [comment]
For all file types, when exported, there should be 2 new fields, meridianDataSource and meridianQueryName added to the properties of all features.

meridianDataSource is the prettified datasource name (Mock for mock, Fake for Fake, ect)
meridianQueryName is the query name given for the layer the point is in.

**Comment by tdressel** [comment]
Passed on local branch

**Comment by tdressel** [comment]
Passed in develop
