### ISSUE TITLE
Data grid filter is case sensitive.

### ISSUE THREAD

**Issue by tdressel** [ozone-development/meridian#570]
It shouldn't be.

If I am searching on a field that has uppercase and lowercase I might not remember which letters were uppercase or lower case in order to type my search correctly.

**Comment by synAe** [comment]
The data filter should now correctly filter case insensitive:

e.g.
-FAKE
-Fake
-fAKe

**Comment by tdressel** [comment]
Passed on local branch

**Comment by tdressel** [comment]
Passed on dev.
