### ISSUE TITLE
CMAPI: delete layer Fixes

### ISSUE THREAD

**Issue by cwilmsen** [ozone-development/meridian#577]
Fix it so that deleting layers does not break clustering.

**Comment by cwilmsen** [comment]
This ended up being bigger than I was hoping. I had to clean up timeline some, and a little of the rendering engine.

**Comment by tdressel** [comment]
Tested and passed on local branch bug/577/cmapi-delete.  Was able to create 3 Layers with many plots per each Layer.  Each Layer created a timeline snapshot and the timeline badge totals reflected the same as the clusters every time I added a plot.

**Comment by tdressel** [comment]
Re-tested this on develop then back to the branch.  Behaved the same in both environments.  Ran two queries and plotted several feature points belonging to same overlayid. Changed to Single Point, Heat Map and Cluster View.  Cleared Map.  Reran same queries. Won't change views.

**Comment by tdressel** [comment]
re-pulled branch and still failed on FF17.

**Comment by cwilmsen** [comment]
That is another ticket, #569
