### ISSUE TITLE
Add Bookmark Capability

### ISSUE THREAD

**Issue by synAe** [ozone-development/meridian#581]
Add bookmark capability

The current (and only) avenue of bookmark creation originates from the submenu of a specific snapshot within the timeline (Save.to Bookmarks).

One can access the saved bookmarks via the Bookmark Toggle button in the navigation -- located below the query toggle button.

Clicking the button will open a modal dialog similar to Data History.  Currently, the user will only be able to "Jump" to a bookmark and "Delete" an existing bookmark.

Like Data History, the bookmarks modal will not display and instead show a toaster message if no saved Bookmarks exist.

**Comment by tdressel** [comment]
passed in local branch

**Comment by tdressel** [comment]
passed on develop
