### ISSUE TITLE
HTTP ETags

### ISSUE THREAD

**Issue by jlfoster2** [ozone-development/meridian#588]
Essentially each static resource has a hash or some identifier associated with it. Ideally -- you'd tie this to the version number. 

So when you put out a new build, the server might have tag "AAA". When the client tosses it into their cache, it's stored with etag="AAA". When the client refreshes their page and re-requests the resource, the cache will automatically say "I have 'AAA', what do you have?" Server responds with "I have 'AAA', status 304 Not Modified"

Couple days later, you release a new build to the beta server and you update the server-side tag to be "BBB". Client maintains their cache and hits the webpage. When they re-request each resource, the client says "I have 'AAA' what do you have?" Server responds with "I have 'BBB', we're out of sync, release the old resources from your cache and download the new ones"

http://en.wikipedia.org/wiki/HTTP_ETag

**Comment by cwilmsen** [comment]
Node is already using ETAGs. It looks like we cannot do any better from that angle. It seems that some versions of FF don't use etags usually, but other indicators instead.
