### ISSUE TITLE
Renderer: Drag while over feature

### ISSUE THREAD

**Issue by cwilmsen** [ozone-development/meridian#590]
Make it so that a user can drag while over a feature. 
Add: selector.handlers.feature.stopDown = false to base.js L91

To test:
1. Plot a large polygon via cmapi
2. Click inside of the polygon and try to drag
Expected Results: The map should pan with the mouse.

**Comment by cwilmsen** [comment]
This is done in #591 (enhancement/591/locator-update)

**Comment by tdressel** [comment]
Passed on local branch.

STR:
Opened map in cmapi and chose plot feature channel with the payload below. Selected the "Polygon" and unselected the "Polygon" while firebug was open.....No Errors.

Payload - 
{
"overlayId":"lay1",
"featureId":"example.geojson.1",
"format":"geojson",
"feature":{
"type":"FeatureCollection",
"features":[
{
"type":"Feature",
"geometry":{
"type":"Polygon",
"coordinates":[[
[
10.0,
0.0
],
[
11.0,
0.0
],
[
11.0,
10.0
],
[
10.0,
10.0
],
[
10.0,
0.0
]
]]
},
"properties":{
"p1": "test prop 1"
}
},
{
"type":"Feature",
"geometry":{
"type":"LineString",
"coordinates":[
[
80.0,
3.0
],
[
81.0,
3.0
],
[
81.0,
5.0
],
[
82.0,
2.0
]
]
},
"properties":{

            },
            "name":"crossingLine",
            "id":"id_2",
            "description":"this is a line you don’t want to cross"
        }
    ]
},
"name":"Sample GeoJSON Feature Collection",
"zoom":"true",
"readOnly":"false"
}

**Comment by tdressel** [comment]
Passed on develop.
