### ISSUE TITLE
Locator: Update

### ISSUE THREAD

**Issue by cwilmsen** [ozone-development/meridian#591]
Update the locator to:
-Use extension created  geoJSON
-use callbacks
-use post rendering
-Allow points to be hidden via popup
-Modify rendering engine to work with new stuff

**Comment by cwilmsen** [comment]
There were some issues with having a locator popup open and clicking on the map to close it, but it looks like I fixed it.

**Comment by tdressel** [comment]
Passed on local branch

**Comment by tdressel** [comment]
Passed on develop
