### ISSUE TITLE
Bookmark - Add capability to edit the bookmark name

### ISSUE THREAD

**Issue by synAe** [ozone-development/meridian#598]
Name editing inside bookmark item row (contained in the list) -- save and cancel buttons to commit the name change or cancel the action

For testing:  1) need to confirm the name change on save and 2) closing the dialog and reopening bookmark list

**Comment by jlfoster2** [comment]
@Dale - looking at this now

**Comment by synAe** [comment]
Updated:  
1) input height and button height are in sync
2) when saving a bookmark, the save will not occur and instead show a warning toaster if a bookmark with that queryId already exists
3) column width for data-actions column inside the bookmark list has had the width increased to accommodate for the vertical scrollbar when the list of bookmarks extends beyond the visual height

**Comment by tdressel** [comment]
passed on dev.
