### ISSUE TITLE
Export To Form displays queries that it cannot handle the export.

### ISSUE THREAD

**Issue by tdressel** [ozone-development/meridian#609]
Export To form displays queries it cannot handle therefore when select Export All it does not make an Export To format available.

Steps used to verify:
Run several types of queries and upload different kinds of files
Go to Export Button on Menu Bar
When Export To Form displays, check top checkbox to enable all queries
RESULTS- Export To is blank.  The user doesnt know that previously uploaded files and certain queries cannot be exported.
SUGGESTION - Maybe gray the certain queries out on form or do not display them.

**Comment by tdressel** [comment]
Passed on branch

**Comment by cwilmsen** [comment]
This ticket changed to be that uploaded files can now be exported, and thus there are no datasources that cannot be exported.

**Comment by tdressel** [comment]
Passed on develop.
