### ISSUE TITLE
ZoomIn/ZoomOut buttons do not reset their colors after a click.

### ISSUE THREAD

**Issue by jrdrgz** [ozone-development/meridian#613]
When you press the zoomIn or the zoomOut buttons in the top left corner, it keeps their 'pressed' state instead of resetting to the 'non-pressed' state. 
Pressed state: darker blue
non-pressed state: lighter blue

Both buttons should go back to the light blue color.

**Comment by tdressel** [comment]
Passed on local branch

**Comment by tdressel** [comment]
Passed on develop.
