### ISSUE TITLE
Snapshot Menu:  Menu Disappears on Hover

### ISSUE THREAD

**Issue by synAe** [ozone-development/meridian#615]
Using the query tool, draw a marquee that will yield large results.  
Populate fields in the Query Tool, click Submit.
While the query is running and when the snapshot is added to the timeline, click the gear icon to display the snapshot menu.  
Mouseover and click Save to Bookmarks.

The menu disappears when hovering over to click and select a menu item.  
The snapshot menu should not preemptively disappear.

**Comment by cwilmsen** [comment]
It's not very responsive with too much data, but it doesn't go away.

**Comment by synAe** [comment]
The responsiveness of the menu?  The lack of responsiveness exists prior to the z-index change, but at least one is able to hover over and click on a menu list item vs. the previous situation

**Comment by tdressel** [comment]
Passed on develop.
