### ISSUE TITLE
Export: Allow exported files to be named

### ISSUE THREAD

**Issue by cwilmsen** [ozone-development/meridian#619]
The export picker should have a new field for KML, CSV, and geoJSON files for the file name. For now, it should default to results.{{filetype}}

The server needs to be set up to be able to recognize and handle such a file request.

**Comment by cwilmsen** [comment]
You can now choose any valid file name you want for file exports. The file should come back with the name given.
If the extension given for the file (or if none is given), the correct one will be added. This is case insensitive.
The export will fail if you use reserved characters in your file name ( \"&/:*<>| ), and put up a toastr.

You can test this by using the export picker.

**Comment by tdressel** [comment]
Passed on local branch
