### ISSUE TITLE
Create Drawing Tool  --  Rectangle

### ISSUE THREAD

**Issue by Bill345** [ozone-development/meridian#620]
Create a drawing tool to allow the user to draw a rectangle on the map.  This tool will be separate from the query tool.  The coordinates created by the rectangle on the map will be published on a channel to allow another application to grab the coordinates and do something with them.  This will be done in OL 2.  

--separate button on the tool bar
--separate channel for the publish operation, use CMAPI channel if available, create new channel if needed
--future work will add point radius and complex polygons to the available geometries available to the user

**Comment by cwilmsen** [comment]
It currently has hbs and css files that are not being used, and show be removed. 
In map/layers Line 601, a duplicate variable boundingBox was added, and should be removed.

In draw.js, do we want _aoi to be added to everything? The ids are already random. Something that Needs to be fixed is that you cannot have multiple features with the same featureId and id. Lines 48 and 50 hard code '_aoi' as the featureId and Id. These need to be made into UUIDs or something.

Also, do we want each shape on it's own layer? I thought we were putting all drawn shapes into one layer.

The object on line 66 should be moved into line 77. (Does it need to be stringified?)

**Comment by cwilmsen** [comment]
Also, in query.js, if query is not active, populateCoordinates should not be run (move it into the if statement)

**Comment by synAe** [comment]
-updated per chris' suggestions
Feedback from John:  gutted the create layer and add shapeParams + shapeLayer to layers.js in open layers
Need feedback that this is correct

**Comment by tdressel** [comment]
Passed on Chrome and FF17

**Comment by cwilmsen** [comment]
Most of the issues in my last statements were not fixed.
-There is still an empty draw-toggle.css file
-There is a new console.log in timeline-publisher
-There is still an extra boundingbox var in layers.js (you should just revert it back to develop)
-draw.js
--left over console.log
--Still uses a static featureId
--Line 78 (without any changes) is missing a ;
--Double quotes on the bottom message pub
--query.js still has populate coordinates outside of the if(isActive) block, which runs it when it shouldn't

**Comment by synAe** [comment]
Hmm I think you had an older commit of the branch, but I:

-removed the empty css / updated the main.js
-removed other console.log

checked in to origin

**Comment by cwilmsen** [comment]
That does seem to be the issue. The code looks good, but I still need to test it.

**Comment by tdressel** [comment]
Passed on develop
