### ISSUE TITLE
Metadata: Split parts

### ISSUE THREAD

**Issue by cwilmsen** [ozone-development/meridian#625]
Make it so that metadata properties that are required by all data to not be in rawQuery, but are one level up.
This will affect requery, elastic, and bookmarks.

**Comment by cwilmsen** [comment]
NOTES FOR TESTING:
-You must clean out your elastic server (either through head or copy paste an empty instance in)
-AFTER THAT, restart your node server
-AFTER THAT, you can start testing

To Test: (do for both fake and mock data)
- Run a query/ see data
- Bookmark query (on new query and restored query)
- requery: All boxes should be filled out

**Comment by tdressel** [comment]
Passed on local branch

**Comment by jrdrgz** [comment]
Tested and everything works.
I'm able to

**Comment by tdressel** [comment]
Requery tool prompt is not displaying when requerying.  FAILED on develop.

**Comment by jlfoster2** [comment]
fixed on dev
