### ISSUE TITLE
Modes: Only load needed extensions

### ISSUE THREAD

**Issue by cwilmsen** [ozone-development/meridian#627]
Make it so that modes only load the extensions that are needed for the components loaded. Possible methods include:
-Separate app.js files for each mode
-a single app.js file that checks what components are there, and then loading related extensions
-Put a list of required extensions in each index.html, which app.js loads
-Server checking for required extensions based on  index.html (probably not a good idea)

**Comment by cwilmsen** [comment]
Went with separate app.js files for each mode.
I also added a helper in the cmapi test harness so that you only have to change the iframe url in the index file.

To Test:
-Normal operation of /
-CMAPI harness test of: /, /basic, /basic-with-settings, embedded, dashboard
-Test of /admin

**Comment by tdressel** [comment]
Passed on local branch.

**Comment by jrdrgz** [comment]
Tested and merged into develop.

**Comment by tdressel** [comment]
Passed on develop.
