### ISSUE TITLE
Combine pub/sub files into 1 to improve applicaiton load time

### ISSUE THREAD

**Issue by jlfoster2** [ozone-development/meridian#628]

**Comment by tdressel** [comment]
Single Point View doesn't do anything and gives firebug error :
TypeError: mediator.publishNotification is not a function
[Break On This Error] 	

"body": notificationTemplate()

HeatMap View doesn't  do anything and gives firebug error:
TypeError: mediator.setVisualMode is not a function
[Break On This Error] 	

mediator.setVisualMode({'mode': targetVisualMode});

**Comment by tdressel** [comment]
Tested on develop. Uncaught TypeError: mediator.publishConfirmation is not a function(anonymous function) @ notification-modal.js:25jQuery.event.dispatch @ jquery.js:4624$event.dispatch @ jquery.event.drag-2.2.js:374elemData.handle @ jquery.js:4292
