### ISSUE TITLE
Bookmark - Save Bookmark

### ISSUE THREAD

**Issue by synAe** [ozone-development/meridian#632]
Select an existing Bookmark to edit.
Clear input field, ensure the input field is empty.
Click save.

Expected Result:  Clicking Save button should not commit, but should instead display a toaster message similar to that when pressing enter when the input field is empty.

**Comment by tdressel** [comment]
Passed on develop.  Was able to bookmark all queries except uploaded files.  The Save to Bookmark option was greyed out for those.
