### ISSUE TITLE
Unable to save bookmark when query returns no results.

### ISSUE THREAD

**Issue by jrdrgz** [ozone-development/meridian#638]
Console shows the following error: GET https://localhost:3000/metadata/query/<id> 500 (Internal Server Error)

Even if no results can be found, the user should be able to store the bookmark, zoom to the area and re-run the query to try again. Our current implementation provides lots of data but real world data sources will not always return data in certain areas, especially if the query params are very specific. 

To replicate the problem:
perform a query 1/4th of the size of the mouse pointer.
Once you get no results back, try saving the bookmark using the timeline.
No message is displayed and the error mentioned above can be seen in the browser dev tools console.

**Comment by tdressel** [comment]
Passed on dev
