### ISSUE TITLE
Nginx

### ISSUE THREAD

**Issue by cwilmsen** [ozone-development/meridian#640]
Include an nginx server between client and node that serves all static content.

**Comment by cwilmsen** [comment]
PLEASE TALK TO ME BEFORE TESTING THIS!! 
There is a lot of extra setup for it.

**Comment by cwilmsen** [comment]
Time improvement:
                          before                 after
Not Cached       6.5-7.5 s            4-4.33s
Cached              5.9s                        3s

**Comment by cwilmsen** [comment]
Tiff, this is ready to be tested by you. Bill got it to work, but I will have to help you get it working.

**Comment by tdressel** [comment]
Errors on both Chrome and FF 34 - Location Service Bad Gateway when using Locator Tool. Data Service failed running a query.

**Comment by tdressel** [comment]
Disregard^
