### ISSUE TITLE
Upload Data: Not a datasource

### ISSUE THREAD

**Issue by cwilmsen** [ozone-development/meridian#642]
Upload data is not a datasource, but is marked as one. Remove the extension code that puts it in the queue.

**Comment by cwilmsen** [comment]
To test: Upload should not be an option in the query tool datasource dropdown.

**Comment by tdressel** [comment]
Passed on local branch

**Comment by tdressel** [comment]
Passed on Chrome in develop branch.  FF17 map is still hanging.
