### ISSUE TITLE
Basemap gallery toggle is broke

### ISSUE THREAD

**Issue by tdressel** [ozone-development/meridian#646]
STR-
Go to Meridian map
Toggle Basemap Gallery 
RESULTS - Nothing. Firebug error : TypeError: mediator.closeBasemapGallery is not a function
[Break On This Error] 	mediator.closeBasemapGallery();
EXPECTED RESULTS - Should turn basemap Gallery off and on.
Issue in both CMAPI and Regular mode.

**Comment by cwilmsen** [comment]
Does anyone besides Tiff have this problem? Develop basemap gallery toggle works fine for me on Chrome and FF.

**Comment by synAe** [comment]
Win8 + FF 37.0.2  and Chrome 42.0.23.11.90m (32bit) works

FF17.0.1 can't get past the Loading Meridian issue to confirm (unrelated)

**Comment by tdressel** [comment]
Passed on develop.

**Comment by jlfoster2** [comment]
@tdressel - this was still broke.  Works on both FF and Chrome now.  Can you retest?
