### ISSUE TITLE
Coordinate converter errors

### ISSUE THREAD

**Issue by jrdrgz** [ozone-development/meridian#651]
UTM to DD: Must not use a default precision. Line 799: precision should default to null for logic to work.

MRGS to UTM: Easting and Northing is not being calculated correctly. Numbers starting with 0 will become shorter after the parseInt() call. Line: 1197-1198: east.toString().length and north.toString().length must be replaced with the variable mgrsPrecision.

**Comment by tdressel** [comment]
Tested successfully UTM - 32U4395965967780
Tested successfully MGRS - 32U ME 3959667780
Tested successfully DD - 53.8549999695675, 8.08167491570285

**Refresh map after each location.
