### ISSUE TITLE
Load Time: r.js

### ISSUE THREAD

**Issue by cwilmsen** [ozone-development/meridian#652]
Use r.js to combine and minify files.

**Comment by cwilmsen** [comment]
This combines all of the components to run with their own main.js file. Extensions are unchanged. 
To test:
-Go to ...../meridian
-Checkout feature/652/rjs
-Run 'node node_modules/grunt-contrib-requirejs/node_modules/requirejs/bin/r.js -o ./app/app.build.js'
-Start up your elastic server
-Run 'node app /app-built'
- Try things out
The modes should also work. You will notice what all the components (except rendering engine, which is too different to combine) only load their main.js file, and that it is very minified.

**Comment by tdressel** [comment]
Tested on local branch.  Was running slow a couple times for me but then picked up. Not sure if it was my laptop or not.  John is testing also.
