### ISSUE TITLE
654: #3 Meridian Help is broke

### ISSUE THREAD

**Issue by tdressel** [ozone-development/meridian#660]
ON DEVELOP
STR-
Go to Map
Choose Meridian Help
RESULTS - Nothing.  Error in console says :100: aura_1: Error caught in listener 'support.open', called with arguments:  [] 
Error: mediator.publishOpening is not a function TypeError: mediator.publishOpening is not a function {stack: (...), message: "mediator.publishOpening is not a function"} []Logger.write @ logger.js:43Logger.error @ logger.js:55callback @ mediator.js:46EventEmitter.emit @ eventemitter2.js:332app.sandbox.emit @ mediator.js:101exposed.openSupport @ support-toggle-mediator.js:17(anonymous function) @ support-toggle.js:26jQuery.event.dispatch @ jquery.js:4624$event.dispatch @ jquery.event.drag-2.2.js:374elemData.handle @ jquery.js:4292

EXPECTED RESULTS - Should open meridian Help Menu

**Comment by cwilmsen** [comment]
I think that this is fixed in the #656 branch
