### ISSUE TITLE
CMAPI - map.feature.plot does not update timeline total

### ISSUE THREAD

**Issue by tdressel** [ozone-development/meridian#676]
STR-
Go to https://localhost:3000/cmapi/
Call map.feature.plot 5 times
RESULTS - 5 features plot on the map. Timeline displays but total on timeline reflects zero total.
EXPECTED RESULTS - 5 features plot on the map. Timeline should display with the same total five.

**Comment by synAe** [comment]
@cwilmsen :  I believe the timeline updating correctly is fixed in either #671 or  #677, however, on back-to-back plots of the same payload (same featureId), the cluster number still increases?  (Timeline does not), Timeline number should not increase if the featureId is still the same, correct?

**Comment by cwilmsen** [comment]
I agree. I don't see this issue. Make sure you are not using the same featureId when plotting. It (correctly) doesn't work when you use the same featureId.

**Comment by cwilmsen** [comment]
No Pull Request

**Comment by synAe** [comment]
fixed via #671

**Comment by tdressel** [comment]
Steps used to verify:
Go to https://localhost:3000/cmapi/
Call map.feature.plot 5 times 
***You have to change the feature name each time. f1, f2,f3,f4 etc/
RESULTS - 5 features plot on the map. Timeline displays 5 also
