### ISSUE TITLE
CMAPI - map.view.center.feature (source and unit test)

### ISSUE THREAD

**Issue by jlfoster2** [ozone-development/meridian#678]
Add CMAPI channel to comply with spec.  Not sure if implementation is already there so please validate.  If so, go ahead an write test to back it.

**Comment by synAe** [comment]
This is a specific fix for map.view.center.feature.  The map.view.center.overlay and map.feature.plot.batch channels aren't the fixed version in this branch -- will not function in /CMAPI

**Comment by synAe** [comment]
Updated with merge from develop

**Comment by tdressel** [comment]
passed on develop
