### ISSUE TITLE
Admin Dashboard is not loading SlickGrid

### ISSUE THREAD

**Issue by synAe** [ozone-development/meridian#681]
The Admin Dashboard is not loading the SlickGrid CSS files and as a result, the data grid does not display when a user submits a query.

Expected result:  grid should now display

**Comment by tdressel** [comment]
https://localhost/admin page not loading.

**Comment by synAe** [comment]
Just switched to bug/681/admingrid-display:
NGINX running, elasticsearch running, node running
pulled on develop and attempted to merge develop into this branch, but was already up to date
Did git diff and git status, no differences showing up
Can view in both FF38 and Chrome 43 on PC Windows 8

**Comment by jlfoster2** [comment]
Looks good to me.  passing it

**Comment by tdressel** [comment]
404 not found for me on develop.
