### ISSUE TITLE
CMAPI:  Fix channels broken from adding a sessionId

### ISSUE THREAD

**Issue by synAe** [ozone-development/meridian#685]
The channels that fail their mocha unit tests need to be fixed:
-map.overlay.create, base
-map.overlay.create, edge 1
-map.overlay.create, edge 2
-map.overlay.hide, base
-map.overlay.hide, edge 1
-map.overlay.show, edge 1

**Comment by synAe** [comment]
UPDATE:  Apparently some of the code for the map.view.center.overlay unit test was never pushed up for ticket #635, which was then merged into develop.  develop never received this code.  Seth had a local copy of the correct code for this channel.  I am inserting it into this branch.  As a result, the code for map.view.center.overlay should supersede the code in #677 for the same channel

**Comment by tdressel** [comment]
map.feature.hide is broke
map.feature.plot.batch is broke
map.view.center.overlay doesnt do anything
map.view.center.feature doesnt do anything

**Comment by synAe** [comment]
For purposes of this ticket, these channels will be non functional in /CMAPI and /MOCHA
-map.feature.hide fix is addressed in ticket #671
-map.feature.plot.batch fix is addressed in ticket #672
-map.view.center.overlay is addressed in ticket #
-map.view.center.feature is addressed in ticket #678

**Comment by tdressel** [comment]
All except map.feature.plot.batch works.

**Comment by jlfoster2** [comment]
I think we can disregard the plot batch...

**Comment by Bill345** [comment]
I agree, we can disregard plot batch at this time.
