### ISSUE TITLE
Return button is not fast enough when specifying a location.

### ISSUE THREAD

**Issue by tdressel** [ozone-development/meridian#93]
STR-
GO to Locator Tool
Type in coordinates ENTER/RETURN button on keyboard really fast
RESULTS - Toaster notification says,"No valid location selected.  Please try again"
EXPECTED RESULTS - It should not take that long after typing coordinates to enable the GO button.

**Comment by jlfoster2** [comment]
Assigning to Dale to investigate Steves option.  We may be limited by the services but lets investigate to see if there anything to do be done. This also fits with next release set of requirements.

**Comment by synAe** [comment]
Pushed a version up for review:  bug/93/locator-search

Side Issue:  After typing text, and a set of items populates the dropdown, a user selects one of the items and that populates the locator input field.  After pressing enter or clicking on the GO button, the map jumps to the location and the input is cleared + button disabled

Does this need to be replicated when coordinates are entered?  

e.g.  Enter 7,1 and press enter or click the GO button right away and the user should jump to the location if it exists  -- however, the input field is still populated and the GO button still enabled UNLIKE the text location

**Comment by Bill345** [comment]
Clear the locator field after do a go to.
Do not return focus to the field after doing a go to.

**Comment by synAe** [comment]
Added:

-clear input field
-clear focus
-go button disabled

**Comment by tdressel** [comment]
Passed in local branch

**Comment by tdressel** [comment]
Passed on develop
